---
title: "09_cartogram_migrants"
author: "Duc-Quang Nguyen"
date: "1 September 2016"
output: html_document
---

```{r setup, include=FALSE}
#"dplyr", "magrittr", "countrycode", "scales", 
install.packages(c("rvest", "readxl", "WDI", "eurostat", "devtools", "htmltools", "shiny", 
                   "htmlwidget", "rCharts", "viridis"))
library(devtools)
install_github(ggplot2)
install_github("d-qn/swiTheme")



data.file <- "input/foreignersMap_wb_dw.csv"
library(readr)
library(tidyr)
library(dplyr)
library(magrittr)
library(countrycode)
library(ggplot2)
library(scales)
library(swiMap)
library(swiTheme)

library(cartogram)
library(maptools)
library(cartogram)
library(rgdal)
library(sp)
```


```{r load data}
data.read <- read_csv( file = data.file ) %>% select(iso2c, iso3c, pc, abs, EN)

path <- getPathShp("world")
layers <- ogrListLayers(path)[1]
wld <- readOGR(path, layer = layers[1])

idx <- match(wld$ISO3, data.read$iso3c)

wld@data[which(is.na(idx)), 'NAME']
wld@data <- cbind(wld@data, data.read[idx, c('pc', 'abs')])
# Filter
wld <- wld[!is.na(wld$abs) & wld$POP2005 >= 10^5,]
wld <- spTransform(wld, CRS("+init=epsg:4326"))
#afr <- spTransform(wld[wld$abs > 0,], CRS("+init=epsg:3395"))

fwld <- cartogram(wld, "abs", 50, maxSizeError = 2)
#save(fwld, file = "input/cartogram_absMigrants_iter50.Rdata")


par(mfcol=c(1,2))
plot(afr)
plot(fwld)






library(cartogram)
library(tmap)
library(maptools)

data(wrld_simpl)

afr <- wrld_simpl[wrld_simpl$REGION==2,]
afr <- spTransform(afr, CRS("+init=epsg:3395"))

# keep only countries with population > 0
# automatic data cleaning is planend for next release
# one needs to do this manually at the moment
afr <- afr[afr$POP2005>0,]

# construct cartogram
afrc <- cartogram(afr[afr$POP2005>0,], "POP2005", itermax=5)

# plot it
tm_shape(afrc) + tm_fill("POP2005", style="jenks") + tm_borders() + tm_layout(frame=F)


```